---
title: "COVID-19 Vaccine Rollout"
author: "David Jackson"
date: "1/28/2021 90:00 PM/EST"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,error = FALSE)

library(ggplot2)
library(scales)
library(dplyr)
library(readxl)
library(forecast)
library(RSQLite)
library(plotly)
```

## Our World In Data Vaccine Plots

```{r}
rm(list=ls())
source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVID-19-DB/OURWORLD.sqlite3")
SWE <- dbGetQuery(db,"select * from OWID")
SWE$date <- as.Date(SWE$date)
SWE <- SWE[order(SWE$date),]
df <- SWE %>%select(date,location,iso_code,new_vaccinations,
                    new_vaccinations_smoothed,total_vaccinations,population)
                    
# df$VMA <- ma(df$new_vaccinations,6,centre=TRUE)

dbDisconnect(db)
```
```{r}
World <- df %>% filter(location=="World" & date >="2020-12-10") 
```

### Plot of New Vaccinations for the World by Day

```{r}
ggplot(World) + geom_line(aes(x=date,y=total_vaccinations)) +
  scale_y_continuous(labels=comma) + 
  labs(title="Worldwide Total Vaccinations")
```

### Total New Vaccinations by Country

```{r}
vaccine_date <- df %>% filter(location !="World") %>% na.omit() %>%
  group_by(date) %>% summarise(Total = sum(new_vaccinations))
    

```
```{r}
  ggplot(vaccine_date) + geom_line(aes(x=date,y=Total)) + geom_smooth(aes(x=date,y=Total)) +
    labs(title="Worldwide New Vaccinations by Date") +
    scale_y_continuous(labels=comma)
```

### Total Vaccinations by County (Top 5)

```{r}
vaccine_country <- df %>% filter(location !="World") %>% na.omit() %>%
  group_by(location) %>% summarise(Total = sum(new_vaccinations)) %>%
  arrange %>% top_n(5,Total)

```
```{r}
 ggplot(vaccine_country) + geom_col(aes(x=location,y=Total)) +
  scale_y_continuous(labels=comma) +
  labs(title="Top Five Countries by New Vaccinations")
  
  
```

### Plot of New and Total Vaccination for Israel

```{r}
Israel <- df %>% filter(location =="Israel") %>% na.omit()
```
```{r}
p1 <- ggplot(Israel) + geom_line(aes(x=date,y=new_vaccinations)) +
  scale_y_continuous(labels=comma) +
  labs(title="Israel New Vaccinations By Date") +
  geom_smooth(aes(x=date,y=new_vaccinations))
```
```{r}
p2 <- ggplot(Israel) + geom_line(aes(x=date,y=total_vaccinations)) +
  scale_y_continuous(labels=comma) +
  labs(title="Israel Total Vaccinations By Date") 

```
```{r}
Israel$Rate <- Israel$total_vaccinations/Israel$population
p3 <- ggplot(Israel) + geom_line(aes(x=date,y=Rate)) +
  scale_y_continuous(labels=percent) +
  labs(title="Israel vaccination Rate By Day")


ggplotly(p1)
ggplotly(p2)
ggplotly(p3)
```

### US Vaccnations By Date


```{r}
US <- df %>% filter(location =="United States") %>% na.omit()
```
```{r}
p5 <- ggplot(US) + geom_line(aes(x=date,y=new_vaccinations)) +
  scale_y_continuous(labels=comma) +
  labs(title="US New Vaccinations By Date") +
  geom_smooth(aes(x=date,y=new_vaccinations))
```
```{r}
p6 <- ggplot(US) + geom_line(aes(x=date,y=total_vaccinations)) +
  scale_y_continuous(labels=comma) +
  labs(title="US Total Vaccinations By Date") 

```

```{r}
US$Rate <- US$total_vaccinations/US$population
p7 <- ggplot(US) + geom_line(aes(x=date,y=Rate)) +
  scale_y_continuous(labels=percent) +
  labs(title="US vaccination Rate By Day")
ggplotly(p5)
ggplotly(p6)
ggplotly(p7)

```

### Spain Vaccnations By Date

```{r}
US <- df %>% filter(location =="Spain") %>% na.omit()
```
```{r}
p8 <- ggplot(US) + geom_line(aes(x=date,y=new_vaccinations)) +
  scale_y_continuous(labels=comma) +
  labs(title="Spai nNew Vaccinations By Date") +
  geom_smooth(aes(x=date,y=new_vaccinations))
```
```{r}
p9 <- ggplot(US) + geom_line(aes(x=date,y=total_vaccinations)) +
  scale_y_continuous(labels=comma) +
  labs(title="Spain Total Vaccinations By Date") 
ggplotly(p8)
ggplotly(p9)

```

```{r}
US$Rate <- US$total_vaccinations/US$population
p10 <- ggplot(US) + geom_line(aes(x=date,y=Rate)) +
  scale_y_continuous(labels=percent) +
  labs(title="Spain vaccination Rate By Day")
ggplotly(p10)
```