---
title: 'Warp Speed: Vaccine Rollout'
author: "David Jackson"
date: "1/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,error = FALSE)

library(ggplot2)
library(scales)
library(dplyr)
library(readxl)
library(forecast)
library(RSQLite)
library(plotly)
```
```{r}
## Our World In Data Vaccine Plots
rm(list=ls())
source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVID-19-DB/OURWORLD.sqlite3")
df <- dbGetQuery(db,"select * from OWID where location = 'United States'")
df$date <- as.Date(df$date)
df <- df[order(df$date),]
US <- df %>%select(date,location,iso_code,new_vaccinations,
                    new_vaccinations_smoothed,total_vaccinations,population) 
dbDisconnect(db)
```

### US Vaccnations By Date


```{r}
summary(df$new_vaccinations)
```
```{r}
p5 <- ggplot(US) + geom_line(aes(x=date,y=new_vaccinations)) +
  scale_y_continuous(labels=comma) +
  labs(title="US New Vaccinations By Date") +
  geom_smooth(aes(x=date,y=new_vaccinations))
```
```{r}
p6 <- ggplot(US) + geom_line(aes(x=date,y=total_vaccinations)) +
  scale_y_continuous(labels=comma) +
  labs(title="US Total Vaccinations By Date") 

```

```{r}
US$Rate <- US$total_vaccinations/US$population
p7 <- ggplot(US) + geom_line(aes(x=date,y=Rate)) +
  scale_y_continuous(labels=percent) +
  labs(title="US vaccination Rate By Day")
ggplotly(p5)
ggplotly(p6)
ggplotly(p7)

```

#### Predict 50% vaccination Rate

```{r}
US$population/2* mean(US$new_vaccinations)
```


